### ISSUE TITLE
Usage with byte array

### ISSUE THREAD

**Issue by kbrewer08** [GoldenGnu/java-dds#8]
Not so much an issue, but a question. I have a decompressed unity asset bundle where I have raw image data in a byte array. I know the width, I know the height, I know it's DXT5, and I have the raw image data itself (it does not include any meta). How can I use this in this case? The only read method I saw in DDSImageReader was wanting an index and some other stuff, and I've no idea what that means in the context of my purely-image-data byte array.

**Comment by GoldenGnu** [comment]
I'm not actively developing this library anymore.
But, I will try to fix bugs, if you find any.

The library only reads DDS files, it does not write them.
Encoding DDS files is a lot more complicated than decoding them and since I didn't need to write the DDS files, I never added that feature.

The library is designed as a ImageIO plugin. To read DDS files, you need to:
1) Include the library in the class path
2) Use ImageIO to read the DDS file: https://docs.oracle.com/javase/tutorial/2d/images/loadimage.html

If you have any additional questions, just, post here again, I will help the best I can.

**Comment by kbrewer08** [comment]
Well decompression is exactly what I was talking about. Except I just have the raw image data - no header/meta data and not a file; it's byte array. If decoding a byte array isn't supported, I'll just have to look through the DXT1/5 decoding parts and adapt them to my application.

**Comment by GoldenGnu** [comment]
It's not supported out of the box, no. But, all the code needed to decompress DXT5 is there.

You need to call the following method for each line:
https://github.com/GoldenGnu/java-dds/blob/master/src/main/java/net/nikr/dds/DDSLineReader.java#L102
For that you will need to create a valid DDSHeader
https://github.com/GoldenGnu/java-dds/blob/master/src/main/java/net/nikr/dds/DDSHeader.java

That will fill the byte[][] banks with the decompressed data

There is a bit more logic need to make it into an image, for that see: 
https://github.com/GoldenGnu/java-dds/blob/master/src/main/java/net/nikr/dds/DDSImageReader.java#L125

It's a very long since I have looked at the code, but, I will be happy to help the best I can...

**Comment by kbrewer08** [comment]
Yeah, I'll just have to look through it. Honestly, I already have my own DXT5 decompression method, but there's a lot of noise in what should be 100% transparent areas. Which is probably due to my having translated it from javascript and python, so some language quirks have popped up here and there causing several issues. But since this project is already in java, it should be a much better adaptation.

**Comment by GoldenGnu** [comment]
I ported most of the code from the GiMP DDS plugin. I think it's in some flavor of C. At least it was close enough to java, that I didn't have to change stuff like bit operators etc. 
But, there was still quite a bit of trail and error involved, before everything worked perfectly.

Happy coding and good luck with your project.

**Comment by kbrewer08** [comment]
I copied the relevant bits into my application and it works great, however, the image is upside down. I am using null for the ImageReadParam argument.

**Comment by GoldenGnu** [comment]
What way is it flipped? Horizontal or vertical?

**Comment by kbrewer08** [comment]
Well flipped seems to be a technical term after a bit of googling, so I used that. More specifically, it's upside down, and mirrored.

**Comment by GoldenGnu** [comment]
It's one of two things, the input is in the wrong order or the output is in the wrong order.
I can't tell if it's one or the other, without seeing your code.

The code does assume you're using little endian for the input byte array
```java
stream.setByteOrder(ByteOrder.LITTLE_ENDIAN);
```
...but, I'm not sure if that matters or not

**Comment by kbrewer08** [comment]
I think the only thing the endianess refers to is the color data in each block to be decoded. The colors and alpha are perfect, the columns from left to right are perfect, it's just flipped horizontally.

I  mostly copied and pasted the minimum of the most relevant parts, so when you look at it you'll see things missing. This all relates to my source containing only the raw image data itself in the form of a byte stream The source is a decompressed Unity asset bundle, not a MS DDS file, so no header. This means anything related to the header and ImageIO streams got cut. This is specifically DXT5.

	public class DXTDecoder {

		private static final int BANK_RED = 0;
		private static final int BANK_GREEN = 1;
		private static final int BANK_BLUE = 2;
		private static final int BANK_ALPHA = 3;

		private static final int LINES_PER_READ = 4;
		private static final int COLORS_PER_READ = 4;

		private byte[][][] linesColor;
		private int lineNumber = 0;

		public BufferedImage decode(ImageReadParam param, int format, int width, int height, byte[] bytes) {
			Rectangle sourceRegion = new Rectangle(0, 0, width, height);

			int sourceXSubsampling = 1;
			int sourceYSubsampling = 1;

			int[] sourceBands = null;
			int[] destinationBands = null;

			Point destinationOffset = new Point(0, 0);

			BufferedImage dst = new BufferedImage(width, height, BufferedImage.TYPE_4BYTE_ABGR);

			WritableRaster wrSrc = Raster.createBandedRaster(DataBuffer.TYPE_BYTE, width, 1, 4, new Point(0, 0));

			byte[][] banks = ((DataBufferByte) wrSrc.getDataBuffer()).getBankData();

			WritableRaster wrDst = dst.getRaster();

			int dstMinX = wrDst.getMinX();
			int dstMaxX = dstMinX + wrDst.getWidth() - 1;
			int dstMinY = wrDst.getMinY();
			int dstMaxY = dstMinY + wrDst.getHeight() - 1;

			if (sourceBands != null) {
				wrSrc = wrSrc.createWritableChild(0, 0, width, 1, 0, 0, sourceBands);
			}

			if (destinationBands != null) {
				wrDst = wrDst.createWritableChild(0, 0, wrDst.getWidth(), wrDst.getHeight(), 0, 0, destinationBands);
			}

			int srcY = 0;
			int[] pixel = wrSrc.getPixel(0, 0, (int[]) null);

			for (srcY = 0; srcY < height; srcY++) {
				// Decode the next row from the DDS file.
				// TODO Can be moved down past the continue/breaks...
				decodeDXT(bytes, format, banks, width, srcY);

				// Reject rows that lie outside the source region, or which are
				// not part of the subsampling.
				if ((srcY < sourceRegion.y)
						|| (srcY >= sourceRegion.y + sourceRegion.height)
						|| (((srcY - sourceRegion.y) % sourceYSubsampling) != 0)) {
					continue;
				}

				// Determine the row's location in the destination.
				int dstY = destinationOffset.y + (srcY - sourceRegion.y) / sourceYSubsampling;
				if (dstY < dstMinY) {
					continue; // The row is above the top of the destination rectangle.
				}

				if (dstY > dstMaxY) {
					break; // The row is below the bottom of the destination rectangle.
				}

				// Copy each subsampled source pixel that fits into the
				// destination rectangle into the destination.
				for (int srcX = sourceRegion.x; srcX < sourceRegion.x + sourceRegion.width; srcX++) {
					if (((srcX - sourceRegion.x) % sourceXSubsampling) != 0) {
						continue;
					}

					int dstX = destinationOffset.x + (srcX - sourceRegion.x) / sourceXSubsampling;
					if (dstX < dstMinX) {
						continue; // The pixel is to the destination rectangle's left.
					}

					if (dstX > dstMaxX) {
						break; // The pixel is to the destination rectangle's right.
					}

					// Copy the pixel. Sub-banding is automatically handled.
					wrSrc.getPixel(srcX, 0, pixel);
					wrDst.setPixel(dstX, dstY, pixel);
				}
			}
			//magic
			return dst;
		}

		private void decodeDXT(byte[] bytes, int format, byte[][] banks, int width, int y) {
			if (lineNumber >= LINES_PER_READ) {
				lineNumber = 0;
			}
			if (lineNumber == 0) {
				//System.out.println("Read line: " + y);
				int fixedWidth = fixSize(width); //Fix "Bad size"
				linesColor = new byte[LINES_PER_READ][(int) Math.max(fixedWidth, 8)][COLORS_PER_READ];
				if (format == 12) {
					for (int x = 0; x < fixedWidth; x = x + 4) {
						decodeAtiAndDxt5AlphaBlock(bytes, 16, 0, x, (16 * fixedWidth / 4 * y / 4), BANK_ALPHA);
						decodeColorBlock(bytes, 16, 8, x, (16 * fixedWidth / 4 * y / 4), false);
					}
				} else {
					for (int x = 0; x < fixedWidth; x = x + 4) {
						decodeColorBlock(bytes, 8, 0, x, (8 * fixedWidth / 4 * y / 4), true);
					}
				}
			}
			for (int x = 0; x < width; x++) {
				banks[BANK_RED][x] = linesColor[lineNumber][x][BANK_RED];
				banks[BANK_GREEN][x] = linesColor[lineNumber][x][BANK_GREEN];
				banks[BANK_BLUE][x] = linesColor[lineNumber][x][BANK_BLUE];
				banks[BANK_ALPHA][x] = linesColor[lineNumber][x][BANK_ALPHA];
			}
			lineNumber++;
		}

		private int fixSize(int size) {
			while (size % 4 != 0) {
				size++;
			}
			return size;
		}

		private void decodeAtiAndDxt5AlphaBlock(byte[] bytes, int offset, int start, int x, int lineOffset, int bank) {
			int color0, color1, bits0, bits1, bits2, bits3, bits4, bits5;
			int[] color = new int[8];
			int[] bits = new int[6];

			//Read 8 Bytes
			color0 = bytes[lineOffset + (x / 4 * offset) + (0 + start)] & 0xff;
			color1 = bytes[lineOffset + (x / 4 * offset) + (1 + start)] & 0xff;
			bits0 = bytes[lineOffset + (x / 4 * offset) + (2 + start)] & 0xff;
			bits1 = bytes[lineOffset + (x / 4 * offset) + (3 + start)] & 0xff;
			bits2 = bytes[lineOffset + (x / 4 * offset) + (4 + start)] & 0xff;
			bits3 = bytes[lineOffset + (x / 4 * offset) + (5 + start)] & 0xff;
			bits4 = bytes[lineOffset + (x / 4 * offset) + (6 + start)] & 0xff;
			bits5 = bytes[lineOffset + (x / 4 * offset) + (7 + start)] & 0xff;

			//64bit UNSIGNED LONG - broke up into 6 ints
			bits[0] = bits0 + 256 * (bits1 + 256);
			bits[1] = bits1 + 256 * (bits2 + 256);
			bits[2] = bits2 + 256 * (bits3 + 256);
			bits[3] = bits3 + 256 * (bits4 + 256);
			bits[4] = bits4 + 256 * (bits5);
			bits[5] = bits5;

			//FIXME is not calulated... should:  multiplying by 1/255.
			color[0] = color0 > -128 ? color0 : -1;
			color[1] = color1 > -128 ? color1 : -1;

			if (color0 > color1) {
				color[2] = (6 * color[0] + 1 * color[1]) / 7;
				color[3] = (5 * color[0] + 2 * color[1]) / 7;
				color[4] = (4 * color[0] + 3 * color[1]) / 7;
				color[5] = (3 * color[0] + 4 * color[1]) / 7;
				color[6] = (2 * color[0] + 5 * color[1]) / 7;
				color[7] = (1 * color[0] + 6 * color[1]) / 7;
			} else {
				color[2] = (4 * color[0] + 1 * color[1]) / 5;
				color[3] = (3 * color[0] + 2 * color[1]) / 5;
				color[4] = (2 * color[0] + 3 * color[1]) / 5;
				color[5] = (1 * color[0] + 4 * color[1]) / 5;
				color[6] = 0;
				color[7] = 255;
			}
			int i, bit;
			byte code;
			for (int yi = 0; yi < 4; yi++) {
				for (int xi = 0; xi < 4; xi++) {
					i = (3 * (4 * yi + xi));

					bit = (int) Math.floor(i / 8.0);
					i = i - (bit * 8);

					code = (byte) ((bits[bit] >> i) & 7);

					linesColor[yi][x + xi][bank] = (byte) color[code];
				}
			}
		}

		private void decodeColorBlock(byte[] bytes, int offset, int start, int x, int lineOffset, boolean dxt1) {
			int c0lo, c0hi, c1lo, c1hi, bits0, bits1, bits2, bits3;
			//Read 8 bytes
			c0lo = bytes[lineOffset + (x / 4 * offset) + (0 + start)] & 0xff;
			c0hi = bytes[lineOffset + (x / 4 * offset) + (1 + start)] & 0xff;
			c1lo = bytes[lineOffset + (x / 4 * offset) + (2 + start)] & 0xff;
			c1hi = bytes[lineOffset + (x / 4 * offset) + (3 + start)] & 0xff;
			bits0 = bytes[lineOffset + (x / 4 * offset) + (4 + start)] & 0xff;
			bits1 = bytes[lineOffset + (x / 4 * offset) + (5 + start)] & 0xff;
			bits2 = bytes[lineOffset + (x / 4 * offset) + (6 + start)] & 0xff;
			bits3 = bytes[lineOffset + (x / 4 * offset) + (7 + start)] & 0xff;

			long bits = bits0 + 256 * (bits1 + 256 * (bits2 + 256 * bits3));
			int color0 = (c0lo + c0hi * 256);
			int color1 = (c1lo + c1hi * 256);

			int[][] colorsRGBA = new int[4][4];
			colorsRGBA[0] = unpackRBG565(color0);
			colorsRGBA[1] = unpackRBG565(color1);

			if (color0 > color1) {
				//RGB
				for (int i = 0; i < 3; i++) {
					colorsRGBA[2][i] = ((2 * colorsRGBA[0][i] + colorsRGBA[1][i]) / 3);
					colorsRGBA[3][i] = ((colorsRGBA[0][i] + 2 * colorsRGBA[1][i]) / 3);
				}
				//Transparency 
				colorsRGBA[2][3] = 255;
				colorsRGBA[3][3] = 255;
			} else {
				//RGB
				for (int i = 0; i < 3; i++) {
					colorsRGBA[2][i] = ((colorsRGBA[0][i] + colorsRGBA[1][i]) / 2);
					colorsRGBA[3][i] = 0; //Black or tranperant
				}
				//Transparency 
				colorsRGBA[2][3] = 255;
				if (dxt1) {
					colorsRGBA[3][3] = 0;
				} else {
					colorsRGBA[3][3] = 255;
				}
			}
			int i = 0;
			for (int yi = 0; yi < 4; yi++) {
				for (int xi = 0; xi < 4; xi++) {
					byte code = (byte) ((bits >> i * 2) & 3);
					linesColor[yi][x + xi][BANK_RED] = (byte) colorsRGBA[code][0];
					linesColor[yi][x + xi][BANK_GREEN] = (byte) colorsRGBA[code][1];
					linesColor[yi][x + xi][BANK_BLUE] = (byte) colorsRGBA[code][2];
					if (dxt1) {
						linesColor[yi][x + xi][BANK_ALPHA] = (byte) colorsRGBA[code][3];
					}
					i++;
				}
			}
		}

		private int[] unpackRBG565(int rbg565) {
			int r = (rbg565 >> 11) & 0x1f;
			int g = (rbg565 >> 5) & 0x3f;
			int b = (rbg565) & 0x1f;

			int[] color = new int[4];
			color[0] = (char) ((r << 3) | (r >> 2));
			color[1] = (char) ((g << 2) | (g >> 4));
			color[2] = (char) ((b << 3) | (b >> 2));
			color[3] = 255;

			return color;
		}
	}

**Comment by GoldenGnu** [comment]
I can't see how the above decompression code could flip the image vertical.
If the input `byte[] bytes` was in the wrong orders, I don't think you would get a clear image.
So, I think it's most likely the image is decompressed correctly, but, the image was stored upside-down.

**Comment by kbrewer08** [comment]
Well that was exactly it. Apparently the Unity3D framework stores images upside down (???). So I started dstY at (height - 1) and gave it a -- in the for loop and it sorted me out. Thanks for your assistance!

(This can be closed; just leaving open in case you wanted a final comment).

**Comment by GoldenGnu** [comment]
Good to hear it's finally working. I'm happy to know that my old code is being put to use.
